name: 'VulnAPI Action'
description:
  "GitHub Action to use CerberAuth's VulnAPI to check for vulnerabilities in
  your API"
author: 'CerberAuth'

# Define your inputs here.
inputs:
  version:
    description: 'The version of the VulnAPI to use'
    required: true
    default: 'latest'

  curl:
    description: 'The curl command used to run API vulnerability scans'
    required: false

  openapi:
    description: 'The OpenAPI file used to run API vulnerability scans'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
